# Generated by Django 5.0.3 on 2024-03-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('loan_taken', models.IntegerField()),
                ('loan_remaining', models.IntegerField()),
                ('repayment_time', models.IntegerField()),
                ('loan_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending')], max_length=10)),
            ],
        ),
    ]
