# Generated by Django 5.0.3 on 2024-03-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('ids', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('ids', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('loan_taken', models.IntegerField()),
                ('loan_remaining', models.IntegerField()),
                ('repayment_time', models.IntegerField()),
                ('loan_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
