# Generated by Django 5.0.3 on 2024-03-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0002_admins_customers_delete_admin_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='name',
            new_name='username',
        ),
    ]
