# Generated by Django 5.0.3 on 2024-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0003_rename_name_customers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='loan_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('NOTTAKEN', 'Nottaken')], max_length=10),
        ),
    ]
