# Generated by Django 4.2.6 on 2024-03-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0005_alter_customers_loan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ids', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('loan_taken', models.IntegerField()),
                ('loan_remaining', models.IntegerField()),
                ('repayment_time', models.DateTimeField()),
                ('loan_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Admins',
            new_name='Admin',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
