# Generated by Django 4.2.6 on 2024-03-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0006_customer_rename_admins_admin_delete_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='repayment_time',
            field=models.DateTimeField(null=True),
        ),
    ]
