# Generated by Django 5.0.3 on 2024-03-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0007_alter_customer_repayment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('ids', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('loan_taken', models.IntegerField()),
                ('loan_remaining', models.IntegerField()),
                ('repayment_time', models.DateTimeField(null=True)),
                ('loan_status', models.CharField(max_length=20)),
                ('loan_term', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
